-- member 데이터 초기화
INSERT INTO member (IS_ADMIN, CREATED_AT, MODIFIED_AT, NICKNAME, EMAIL, PASSWORD, PROFILE_IMAGE, REFRESH_TOKEN, SOCIAL_ID, USER_ROLE)
VALUES (false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'testUser1', 'test1@example.com', 'password123', NULL, NULL, NULL, 'USER');

INSERT INTO member (IS_ADMIN, CREATED_AT, MODIFIED_AT, NICKNAME, EMAIL, PASSWORD, PROFILE_IMAGE, REFRESH_TOKEN, SOCIAL_ID, USER_ROLE)
VALUES (false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'testUser2', 'test2@example.com', 'password456', NULL, NULL, NULL, 'USER');

-- celebrity 데이터 초기화
INSERT INTO celebrity (IS_APPROVED, CREATED_AT, MODIFIED_AT, CELEB_NAME, CELEB_GROUP, CELEB_GENDER, CELEB_TYPE, PROFILE_IMAGE)
VALUES (true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '손흥민', '토트넘 홋스퍼', 'MALE', 'SPORT', 'profile1.jpg');

INSERT INTO celebrity (IS_APPROVED, CREATED_AT, MODIFIED_AT, CELEB_NAME, CELEB_GROUP, CELEB_GENDER, CELEB_TYPE, PROFILE_IMAGE)
VALUES (true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '태연', '소녀시대', 'FEMALE','SINGER', 'profile2.jpg');

-- post 데이터 초기화
INSERT INTO post (PARTICIPANTS, TARGET_PRICE, CELEBRITY_CELEB_ID, CREATED_AT, DEADLINE, MODIFIED_AT, WRITER_USER_ID, INTRODUCTION, THUMBNAIL, TITLE)
VALUES (17, 3000000, 1, CURRENT_TIMESTAMP, '2023-09-30T12:00:00', CURRENT_TIMESTAMP, 1, '2023년 10월 7일부터 14일까지 지하철역에서 진행할 예정입니다.', 'Sample Thumbnail URL 1', '손흥민 유럽리그 통산 200골 기념 광고');

INSERT INTO post (PARTICIPANTS, TARGET_PRICE, CELEBRITY_CELEB_ID, CREATED_AT, DEADLINE, MODIFIED_AT, WRITER_USER_ID, INTRODUCTION, THUMBNAIL, TITLE)
VALUES (11, 1500000, 2, CURRENT_TIMESTAMP, '2023-11-25T12:00:00', CURRENT_TIMESTAMP, 2, 'SM사옥으로 보낼 예정입니다.', 'Sample Thumbnail URL 2', '태연 앨범 발매 기념 간식 트럭');

-- comment 데이터 초기화
INSERT INTO comment (WRITER_ID, POST_ID, CONTENT, IS_DELETED, COMMENT_ORDER, CREATED_AT, MODIFIED_AT)
VALUES (1, 1, '손흥민 골 정말 멋졌어요!', false, '1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO comment (WRITER_ID, POST_ID, CONTENT, IS_DELETED, COMMENT_ORDER, CREATED_AT, MODIFIED_AT)
VALUES (2, 2, '태연의 노래 진짜 좋더라고요!', false, '1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO comment (WRITER_ID, POST_ID, CONTENT, IS_DELETED, COMMENT_ORDER, CREATED_AT, MODIFIED_AT)
VALUES (2, 1, '맞아요! 저도 그렇게 생각해요!', false, '1.1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO comment (WRITER_ID, POST_ID, CONTENT, IS_DELETED, COMMENT_ORDER, CREATED_AT, MODIFIED_AT)
VALUES (1, 2, '저도 노래 좋아해서 매일 듣고 있어요!', false, '1.1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
